### PR TITLE
Update basics

### PR DESCRIPTION
**Pull request by DaanVanHauwermeiren**
some minor updates

TODO:
- [ ] update notebooks and so

### CODE REVIEW

**Comment by DaanVanHauwermeiren** [comment]
@MichielStock 

for the clip function, currently this is : `min(0, max(1, x))`.
Should this be changed to : `max(0, min(1, x))`

**Comment by DaanVanHauwermeiren** [comment]
commit fd89bde683e896ec344a1d6562aa84d2328aee39 and 860fb711d1add7efc2d351a948a319c55eec6843 add the features asked in https://github.com/MichielStock/Julia925/pull/21#issuecomment-564704787

**Comment by DaanVanHauwermeiren** [comment]
> @MichielStock
> 
> for the clip function, currently this is : `min(0, max(1, x))`.
> Should this be changed to : `max(0, min(1, x))` ?

fixed in 0c1e87d

**Comment by MichielStock** [comment]
Yes

**Pull request merged**
